#!/home/user/.local/share/virtualenvs/nott-your-timetable-4K2hnzMP/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from nott_your_timetable.nott_your_timetable import main_gui
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main_gui())
