name: Compile Executable

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version of Release to upload to"
        required: true
        type: string
  
permissions:
  contents: read
  
jobs:
  compile-and-upload:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        spec-file: [nott-your-timetable.spec]
        include:
          - os: macos-latest
            shell: bash
            install-dependencies: brew install pygobject3 gtk+3
            extension: .zip
          - os: windows-latest
            shell: msys2 {0}
            install-dependencies: pacman -Syu --noconfirm mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python3-gobject mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-pip
            extension: .exe
          # - spec-file: nott-your-timetable-folder.spec
          # os: windows-latest
          # extension: zip
    defaults:
      run: 
        shell: ${{ matrix.shell }}
        
    runs-on: ${{ matrix.os }}

    env:
      version: ${{ inputs.version || github.event.release.tag_name }}

    steps:
      - name: Installing msys2
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with: 
          update: true
          msystem: mingw64
          
      - uses: actions/checkout@v3
        # with:
          # ref: ${{ env.version }}

      - name: Set up Python "3.10"
        uses: actions/setup-python@v4
        with:
         python-version: "3.10"
         
      - name: Installing System Dependencies
        run: ${{ matrix.install-dependencies }}
         
      - name: Installing nott-your-timetable
        run: |
          python -m pip install -e .
          python -m pip install pyinstaller
      
      - name: Compiling Executable
        run: pyinstaller ${{ matrix.spec-file }}

      #- name: Zipping Folder
      #  if: matrix.spec-file == 'nott-your-timetable-folder.spec'
      #  run: zip -r dist/nott-your-timetable.zip dist/nott-your-timetable

      - run: ls -la dist/

      - name: Making DMG
        if: matrix.os == 'macos-latest'
        # https://stackoverflow.com/questions/286419/how-to-build-a-dmg-mac-os-x-file-on-a-non-mac-platform
        # https://stackoverflow.com/questions/96882/how-do-i-create-a-nice-looking-dmg-for-mac-os-x-using-command-line-tools
        #run: |
        #  dd if=/dev/zero of=dist/nott-your-timetable.dmg bs=1M count=16 status=progress
        #  mkfs.hfsplus -v Install dist/nott-your-timetable.dmg
        run: zip -r dist/nott-your-timetable.zip dist/nott-your-timetable.app
          
      - name: Uploading Executable
        run: gh release upload ${{ inputs.version }} dist/nott-your-timetable${{ matrix.extension }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
