name: Compile Executable

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version of Release to upload to"
        required: true
        type: string
  
permissions:
  contents: read
  
jobs:
  compile-and-upload:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        spec-file: [nott-your-timetable.spec]
        include:
          - os: macos-latest
            shell: bash
            install-dependencies: brew install pygobject3 gtk+3
            extension: application
          - os: windows-latest
            shell: msys2 {0}
            install-dependencies: pacman -Syu --noconfirm mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python3-gobject mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-pip
            extension: exe
          # - spec-file: nott-your-timetable-folder.spec
          # extension: zip
    defaults:
      run: 
        shell: ${{ matrix.shell }}
        
    runs-on: ${{ matrix.os }}

    env:
      version: ${{ inputs.version || github.event.release.tag_name }}

    steps:
      - name: Installing msys2
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with: 
          update: true
          msystem: mingw64
          
      - uses: actions/checkout@v3
        # with:
          # ref: ${{ env.version }}

      - name: Set up Python "3.10"
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"
         
      - name: Installing System Dependencies
        run: ${{ matrix.install-dependencies }}
         
      - name: Installing nott-your-timetable
        run: |
          python -m pip install -e .
          python -m pip install pyinstaller
      
      - name: Compiling Executable
        run: pyinstaller ${{ matrix.spec-file }}

      - name: Zipping Folder
        if: matrix.spec-file == 'nott-your-timetable-folder.spec'
        run: zip -r dist/nott-your-timetable.zip dist/nott-your-timetable
          
      - name: Uploading Executable
        run: gh release upload ${{ inputs.version }} dist/nott-your-timetable.${{ matrix.extension }}
