name: Compile Executable

on:
  release:
    types: [published]
  
permissions:
  contents: read
  
jobs:
  compile-and-upload:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: action/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"
        
      - name: Installing nott-your-timetable
        run: |
          python -m pip install -e .
          python -m pip install pyinstaller
          
      - name: Compiling Executable
        run: pyinstaller $(which nott-your-timetable)
          
      - name: Uploading Executable
        run: gh release upload ${{ env.version }} dist/nott-your-timetable/nott-your-timetable*
