name: Compile Executable

on:
  release:
    types: [published]
  workflow_dispatch:
  
permissions:
  contents: read
  
jobs:
  compile-and-upload:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: macos-latest
            shell: bash
            install-dependencies: brew install pygobject3 gtk+3
          - os: windows-latest
            shell: msys2 {0}
            install-dependencies: pacman -Syu --noconfirm mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python3-gobject
    defaults:
      run: 
        shell: ${{ matrix.shell }}
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Installing msys2
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with: 
          update: true
          msystem: mingw64
          
      - uses: actions/checkout@v3

      - name: Set up Python "3.10"
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"
         
      - name: Installing System Dependencies
        run: ${{ matrix.install-dependencies }}
         
      - name: Installing nott-your-timetable
        run: |
          python -m pip install -e .
          python -m pip install pyinstaller
          
      - name: Compiling Executable
        run: pyinstaller nott-your-timetable.spec
          
      #- name: Uploading Executable
      #  run: gh release upload ${{ env.version }} dist/nott-your-timetable/nott-your-timetable*
