name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing pylint dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Installing system dependencies
      run: sudo apt install -y libgirepository1.0-dev libgtk-4-1 libgtk-4-dev
    - name: Installing python dependencies
      run: python -m pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
